version: "2"

services:
  jass_v1:
    build: .
    environment:
      - MONGO_HOST=mongodb://annouser:whateve4rlogin@mongo/anno
    expose:
      - 5000
    ports:
      - "5000:5000"
    depends_on:
     - mongo

  mongo:
    build: mongo_image
    expose:
      - 27017
      - 28017
    environment:
      - MONGODB_DATABASE=anno
      - MONGODB_USER=annouser
      - MONGODB_PASS=whateve4rlogin
    volumes:
      - /data
